In [6]:
import torch
import torch.nn as nn

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size

        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
        self.i2o = nn.Linear(input_size + hidden_size, output_size)
        self.softmax = nn.LogSoftmax(dim=1)

    def forward(self, input, hidden):
        combined = torch.cat((input, hidden), 1)
        hidden = self.i2h(combined)
        output = self.i2o(combined)
        output = self.softmax(output)
        return output, hidden

    def initHidden(self):
        return torch.zeros(1, self.hidden_size)



In [7]:
criterion = nn.NLLLoss()
learning_rate = 0.005 # If you set this too high, it might explode. If too low, it might not learn

def v2t(vec): #build a tensor form a 2-d list
    tensor = torch.zeros(len(vec), 1, len(vec[0]))
    for vi, v1 in enumerate(vec):
        tensor[vi][0]=torch.tensor(v1)
    return tensor

cur_vec=[[1,2,5],[1,3,4]]
print (cur_vec, v2t(cur_vec))

def train(category_tensor, line_tensor):
    hidden = rnn.initHidden()

    rnn.zero_grad()

    for i in range(line_tensor.size()[0]):
        output, hidden = rnn(line_tensor[i], hidden)
    
    #print(output,category_tensor)
    loss = criterion(output, category_tensor)
    loss.backward()

    # Add parameters' gradients to their values, multiplied by learning rate
    for p in rnn.parameters():
        p.data.add_(-learning_rate, p.grad.data)

    return output, loss.item()

[[1, 2, 5], [1, 3, 4]] tensor([[[1., 2., 5.]],

        [[1., 3., 4.]]])


In [9]:
#start defining the network
n_hidden = 128
n_input=3
rnn = RNN(n_input, n_hidden, 2)
# Keep track of losses for plotting
current_loss = 0
all_losses = []

vector1=[[1,3,4],[2,5,7]]
#vector1=[[0,0,0]]
vector2=[[1,2,2],[3,1,2]]
vector3=[[3,3,4],[2,1,3],[4,7,5]]
vector4=[[1,2,2],[1,1,2]]
vector5=[[3,4,5],[6,5,2]]
vector6=[[1,1,1],[1,2,1],[2,1,1]]
all_vectors=[vector1,vector2,vector3,vector4,vector5,vector6]

    
for i in range(1000):
    for vec in all_vectors:
        ten=v2t(vec)
        line_tensor=ten
        mean=ten.mean()
        val=0
        if mean>3:val=1
        category_tensor=torch.tensor([val])
        
        #print( vec, mean,val)
        output, loss = train(category_tensor, line_tensor)
        current_loss += loss    
        if i>990: print(output,category_tensor)
        
    

tensor([[-4.8270, -0.0080]], grad_fn=<LogSoftmaxBackward>) tensor([1])
tensor([[-0.0201, -3.9186]], grad_fn=<LogSoftmaxBackward>) tensor([0])
tensor([[-8.7334e+00, -1.6117e-04]], grad_fn=<LogSoftmaxBackward>) tensor([1])
tensor([[-0.0214, -3.8551]], grad_fn=<LogSoftmaxBackward>) tensor([0])
tensor([[-4.4021, -0.0123]], grad_fn=<LogSoftmaxBackward>) tensor([1])
tensor([[-2.0695e-03, -6.1815e+00]], grad_fn=<LogSoftmaxBackward>) tensor([0])
tensor([[-4.8281, -0.0080]], grad_fn=<LogSoftmaxBackward>) tensor([1])
tensor([[-0.0200, -3.9197]], grad_fn=<LogSoftmaxBackward>) tensor([0])
tensor([[-8.7354e+00, -1.6069e-04]], grad_fn=<LogSoftmaxBackward>) tensor([1])
tensor([[-0.0214, -3.8562]], grad_fn=<LogSoftmaxBackward>) tensor([0])
tensor([[-4.4032, -0.0123]], grad_fn=<LogSoftmaxBackward>) tensor([1])
tensor([[-2.0652e-03, -6.1836e+00]], grad_fn=<LogSoftmaxBackward>) tensor([0])
tensor([[-4.8292, -0.0080]], grad_fn=<LogSoftmaxBackward>) tensor([1])
tensor([[-0.0200, -3.9207]], grad_fn=<LogSoft