In [85]:
import torch
import torch.nn as nn

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size
        self.lstm = nn.LSTM(input_size, hidden_size)        
        self.hidden2out=nn.Linear(hidden_size,output_size)
        self.out = nn.Linear(hidden_size, output_size)
        
    def forward(self, x, h_state):
        r_out, h_state = self.lstm(x, h_state)
        outs = self.out(r_out)
        return outs, h_state

    def initHidden(self):
        return torch.zeros(1, self.hidden_size)

n_hidden = 32
rnn = RNN(3, n_hidden, 1)


h_state = None      # for initial hidden state
input_tensor=torch.randn(1, 1, 3)
#input_tensor=torch.LongTensor(3).random_(0, 10).view(1,1,3)
out,h_state=rnn(input_tensor,h_state)
print(input_tensor)
print(out)

input_tensor=torch.randn(1, 1, 3)
#input_tensor=torch.LongTensor(3).random_(0, 10).view(1,1,3)
out,h_state=rnn(input_tensor,h_state)
print(input_tensor)
print(out)


tensor([[[-1.3264, -0.5211, -0.2485]]])
tensor([[[-0.0953]]], grad_fn=<AddBackward0>)
tensor([[[-2.1213,  1.5480,  1.0717]]])
tensor([[[-0.0962]]], grad_fn=<AddBackward0>)


In [86]:
#input_tensor=torch.randn(1, 1, 3)
input_tensor=torch.LongTensor(3).random_(0, 10).view(1,1,3)
out,h_state=rnn(input_tensor,h_state)
print(input_tensor)
print(out)


RuntimeError: Expected object of scalar type Float but got scalar type Long for argument #4 'mat1'